{% set name = "libusockets" %}
{% set version = "0.8.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/uNetworking/uSockets/archive/refs/tags/v{{ version }}.tar.gz
    sha256: d14d2efe1df767dbebfb8d6f5b52aa952faf66b30c822fbe464debaa0c5c0b17
    patches:
      - use_libuv.patch
      - disable_ssl_tests.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - openssl
    - libuv
  run:
    - libuv
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -f $PREFIX/include/libusockets.h  # [unix]
    - test -f $PREFIX/lib/libuSockets${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\\libusockets.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\uSockets.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\uSockets.dll exit 1  # [win]

about:
  home: https://github.com/uNetworking/uSockets
  license: Apache-2.0
  license_file: LICENSE
  summary: Miniscule cross-platform eventing, networking & crypto for async applications.

extra:
  recipe-maintainers:
    - traversaro
